### ISSUE TITLE
Add max field check

### ISSUE THREAD

**Issue by onlykeytesting** [onlykey/OnlyKey-Chrome-App#1]
Add max field check

**Comment by rodgolpe** [comment]
Is this referring to form field validation when initializing the OK and/or configuring slots? Some has been implemented:

Slot Config Form
LABEL maxlength=10
USERNAME maxlength=20
DELAY1 min=0 max=255
PASSWORD maxlength=30
CONFIRMPASSWORD maxlength=30

**Comment by onlykey** [comment]
Keith means the form field. The max chars allowed in field should be the same as max in firmware.

**Comment by rodgolpe** [comment]
USERNAME is now 32

Yubi auth fields are:
publicId: 17 (6 bytes + 5 spaces)
privateId: 17 (6 bytes + 5 spaces)
secretKey: 47 (16 bytes + 15 spaces)

U2F auth fields are:
privateId: 95 (32 bytes + 31 spaces)
cert: 3071 (1024 bytes + 1023 spaces)
