### ISSUE TITLE
1 - When using international version disable plausible deniability PIN set in initial setup

### ISSUE THREAD

**Issue by onlykey** [onlykey/OnlyKey-Chrome-App#17]

**Comment by onlykey** [comment]
It looks like it is now disabled but there should ideally be a pop up after setting up SDPIN that says your onlykey is ready since the PD pin does not apply to International Version.

**Comment by onlykey** [comment]
Also change wording on Step 7 to

<h3>Step 7: Enter Plausible Deniability Passcode on OnlyKey keypad</h3>
                    <p>
                        If you are using Two-Factor Authentication and Password Manager (U.S. Version - default) mode you may proceed to enter plausible deniability passcode.
                    </p>
                    <p>
                        WARNING &mdash; Make sure to choose a passcode that you will not forget and that only you know. It is your responsibility to maintain a secure backup of your passcode somewhere just in case you forget.
                    </p>
                    <p>
                        DISCLAIMER &mdash; I understand that entering this passcode will cause OnlyKey to load a second profile and appear as if I am using the Unencrypted Password Manager (International Version) firmware. This may be helpful If I am forced to give up my passcode in some situations but I understand that there is no guarantee here and I am using this feature at my own risk.
                    </p>
                    <label>

**Comment by onlykey** [comment]
If you are using Two-Factor Authentication and Password Manager (U.S. Version - default) mode you may proceed to enter plausible deniability passcode.

WARNING &mdash; Make sure to choose a passcode that you will not forget and that only you know. It is your responsibility to maintain a secure backup of your passcode somewhere just in case you forget.

DISCLAIMER &mdash; I understand that entering this passcode will cause OnlyKey to load a second profile and appear as if I am using the Unencrypted Password Manager (International Version) firmware. This may be helpful If I am forced to give up my passcode in some situations but I understand that there is no guarantee here and I am using this feature at my own risk.

**Comment by rodgolpe** [comment]
This has been completed. I changed the verbiage of the new disclaimer slightly.
