### ISSUE TITLE
2nd Delay  does not work on international version

### ISSUE THREAD

**Issue by jaroszke** [onlykey/OnlyKey-Chrome-App#22]
International version. When programming slot with username, delay, password, delay and 2nd factor.
The 2nd delay after password doesn't work. 

OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 2, 117, 115, 101, 114, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 4, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 3, 50, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 5, 112, 97, 115, 115, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 7, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 6, 50, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 8, 103, 111, 111, 103, 108, 101, 65, 117, 116, 104, 79, 116, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyWizard.js:252 BASE32 value: 3423432423
OnlyKeyWizard.js:255 was converted to HEX: ["df", "35", "be", "6f", "5c", "d6"]
OnlyKeyComm.js:120 SENDING OKSETSLOT to connectionId 43: [255, 255, 255, 255, 230, 4, 9, 223, 53, 190, 111, 92, 214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:120 SENDING OKGETLABELS to connectionId 43: [255, 255, 255, 255, 229, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
OnlyKeyComm.js:151 HandleGetLabels msg: OK
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set Label
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set Label
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set Username
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set Username
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set Delay1
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set Delay1
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set Character1
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set Character1
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set Password
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set Password
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set Delay2
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set Delay2
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set Character2
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set Character2
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set 2FA Type
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set 2FA Type
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: Successfully set TOTP Key
OnlyKeyComm.js:151 HandleGetLabels msg: Successfully set TOTP Key
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |a1
OnlyKeyComm.js:151 HandleGetLabels msg: |a1
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |test2
OnlyKeyComm.js:151 HandleGetLabels msg: |test2
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |
OnlyKeyComm.js:376 Polling...
OnlyKeyComm.js:390 RECEIVED: |
OnlyKeyComm.js:151 HandleGetLabels msg: |

**Comment by jaroszke** [comment]
[delay2serialmonitor.txt](https://github.com/onlykey/OnlyKey-Chrome-App/files/354846/delay2serialmonitor.txt)

**Comment by onlykey** [comment]
fixed
