### ISSUE TITLE
Put limit on Delay fields

### ISSUE THREAD

**Issue by jaroszke** [onlykey/OnlyKey-Chrome-App#24]
@rodgolpe 
Allow only 0-9 to be set on the delay fields. Add in label description 0-9 seconds.

**Comment by rodgolpe** [comment]
Intermediately patched to add the 0-9 label and set maxlength to 1 character. Max and min were not working as expected on `<input type="number" min=0 max=9 />`.

**Comment by onlykey** [comment]
@rodgolpe Tested and working fine
