### ISSUE TITLE
After inserting OnlyKey extension hangs: "Working... Please wait"

### ISSUE THREAD

**Issue by sjvs** [onlykey/OnlyKey-Chrome-App#30]
Hi,

I received my OnlyKey the other day and had a play with it just now. The Chrome Extension asked me to "Please connect your OnlyKey", which I did. It then simply hangs when displaying the red "Working... Please wait" dialog.

I'm on a fairly standard Ubuntu 16.04 machine, and checked that the current user has read/write permission to the OnlyKey device in /dev/usb/.....

Any suggestions would be very welcome. Thanks!

**Comment by onlykey** [comment]
It sounds like you have the same issue as the one listed in our support forum here: https://groups.google.com/forum/#!topic/onlykey/MnD03gQzczg Linux requires a udev rule for write access.

**Comment by sjvs** [comment]
I don't think that's the case: I already put a home-made udev rule in place (which looks a lot like the one you linked to) to make sure I have write access, and ```ls -la``` shows I indeed do have write access. Can you send me a command for me to ```echo``` to the USB device? If I send garbage, it tells me:
```
# echo foobar > /dev/bus/usb/003/002
bash: echo: write error: Invalid argument
```

**Comment by sjvs** [comment]
Never mind - it turned out that I didn't have write access to the relevant /dev/hidrawXXX devices... Sorry!

**Comment by xCapRx** [comment]
I've encountered the same issue on Linux Mint. I also created a MXLinux VM to see if I could get around the issue but no dice.  Tried following the linked instructions but couldn't get anywhere. Couldn't find the 49-teensy.rules file, so I think I'm giving up.

I have to ask why the YubiKey apps work on Linux but the app for OnlyKey doesn't? Can't OnlyKey fix this bug in their software?
