### ISSUE TITLE
1 - Change Slot Config Text

### ISSUE THREAD

**Issue by onlykey** [onlykey/OnlyKey-Chrome-App#31]
The international version firmware does not support Yubikey OTP or U2F but it does support Google Auth. We need to change the wording and also consider in next version to have these options grayed out.

Also, the changing the wording to be less confusing because enter is automatically pressed at end.

Change this from this:
![image](https://cloud.githubusercontent.com/assets/18121756/17708743/51eae95c-63b4-11e6-8c5b-202020e76f90.png)

To this:

[ ] Label
[ ] Username
( ) Tab ( ) Return
[ ] Delay (0-9 seconds)
[ ] Password
Re-enter Password
Options below are for two-factor authentication
[ ] Delay (0-9 Seconds)
( ) Tab ( ) Return
( ) Google Auth OTP  _________________
Options below only work with US Version OnlyKey
( ) Yubikey OTP
( ) U2F (Experimental)

Let me know if this makes sense. For a future version I would like to have the SETTIME which now responds with UNITITIALIZED or UNLOCKED to responds with UNLOCKED_INv0.2-beta.0 or UNLOCKED_USv0.2-beta.0. Also to respond with UNITITIALIZED_INv0.2-beta.2 or  UNITITIALIZED_USv0.2-beta.2

This way the app will know to grey out the options above (Yubikey OTP and U2F (Experimental)) when it receives an UNLOCKED_IN*. We can also remove the initial setup "step 2: Select OnlyKey Mode" because the app will know what mode the OK is using. Make sure that Steps 7 and 8 are disabled for OnlyKey International as this is currently not disabled when a user selects international. It should just jump right to the "Your onlykey is configured, reinsert" message after step 6 for International OnlyKeys.

**Comment by rodgolpe** [comment]
![image](https://cloud.githubusercontent.com/assets/601129/18034748/7a565f12-6d13-11e6-9529-bb59d4306dea.png)

**Comment by onlykey** [comment]
moved tab and return underneath Options below are for two-factor authentication
