### ISSUE TITLE
4 - Lockout period

### ISSUE THREAD

**Issue by onlykeytesting** [onlykey/OnlyKey-Chrome-App#4]
Add field for user to set timeout for OK to lock

**Comment by rodgolpe** [comment]
Waiting for the user-configurable message signature from the firmware team.

**Comment by onlykey** [comment]
Ok the firmware team can add this if onlykeytesting really wants this feature :)  I would add this after the key load stuff in the app though that is first priority. You can add this as OKSETSLOT msg value 11. The next byte after the value will be the timeout in minutes, so 0 - 255, default is 15 minutes.
