### ISSUE TITLE
2 - Add Key Load Field on Setup page for U2F and Yubikey

### ISSUE THREAD

**Issue by onlykey** [onlykey/OnlyKey-Chrome-App#5]
We need three fields for Yubikey
![image](https://cloud.githubusercontent.com/assets/18121756/15381554/70e042dc-1d4e-11e6-819f-e3081a2f1d84.png)
1. Public ID - User will input 6 bytes modhex (I have a modhex convert in firmware so this is no issue to convert)
2. Private ID - User will input 6 bytes hex
3. Secret Key - User will input 16 bytes hex

Two buttons - submit and wipe
The spaces in the three fields should be removed and all three values put into one packet
Packet format to set - “FFFFFFFFE6**6A**vvbhikkuicevf138a824ad07e0f68f664cd4174e43c7f8d2afe9ff3...”
Here we are writing to slot 6 and value 10(A) which is Yubikey. The slot 6 is ignored so this can be set to 0 or really anything it is ignored as Yubikey applies to all slots. 

The message after successfully setting slot is -Successfully set AES Key, Private ID, and Public ID

Packet format to wipe  - “FFFFFFFFE7**6A**... For the wipe the slot is also ignored if the value is set to "0x0A"

The message after successfully wiping slot is - Successfully wiped AES Key, Private ID, and Public ID

We also need two fields for U2F. 
1. U2F Private ID - User will input 32 byte hex
2. U2F Certificate - User will input up to 1024 bytes hex

Two buttons - submit and wipe

Packet format to set U2F Private ID “FFFFFFFFE8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF..."

Packet format to wipe- “FFFFFFFFE9"

Packet format to set U2F Certificate - “FFFFFFFFEA**FF**<fill the rest of the buffer>"
After message ID "EA" the next byte is FF or if it is the last packet the number of bytes in this packet.
“FFFFFFFFEA**FF**<fill the rest of the buffer>"
“FFFFFFFFEA**FF**<fill the rest of the buffer>"
“FFFFFFFFEA**FF**<fill the rest of the buffer>"
“FFFFFFFFEA**FF**<fill the rest of the buffer>"
etc...
Last packet “FFFFFFFFEA**3A**<fill the rest of the buffer>"
I know this is the last packet because the 3A tells me there are 59 bytes in this packet.

Packet format to wipe- “FFFFFFFFEB"

**Comment by rodgolpe** [comment]
Sorry for the late question, but I thought these were not slot-related. However, the example shows:
`Here we are writing to slot 6 and value 10(A) which is Yubikey`

Is that right? If not, what is the format of the message the form should submit?

**Comment by onlykey** [comment]
Good questions, I have updated the example. The slot number is still there it is just ignored so you can set it to 0. Yubikey set/wipe bytes are E6/E7, U2F Priv are E8/E9, U2F Cert are EA/EB. The message the app receives back will be Successfully.....

**Comment by rodgolpe** [comment]
This has been merged into the master branch. There are likely issues.
