### ISSUE TITLE
Slot Labels mismatch

### ISSUE THREAD

**Issue by onlykeytesting** [onlykey/OnlyKey-Chrome-App#6]
Programming label on slot 4a for example returns the label value on slot 3a.

![image](https://cloud.githubusercontent.com/assets/18506949/15400128/68ae9022-1db8-11e6-86a6-55419b283097.png)

**Comment by rodgolpe** [comment]
This is actually <a href="https://github.com/onlykey/OnlyKey-Firmware-US/issues/4">a firmware issue</a>.
