### ISSUE TITLE
Polling for messages during PIN set

### ISSUE THREAD

**Issue by onlykey** [onlykey/OnlyKey-Chrome-App#8]
Currently while you are setting a pin it says las message received UNINITIALIZED. I think that polling is turned off during PIN set. We should turn this on so users can see messages i.e. Successfully set PIN, you must remove OnlyKey and reinsert to configure
or 
Error PIN is not between 7 - 10 characters

**Comment by rodgolpe** [comment]
This is no longer an issue.
